# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.cache/wt} [current_project]
set_property parent.project_path {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/imports/sources_1/new/anode_driver.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/new/bin_to_BCD.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/imports/sources_1/new/clock_converter.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/imports/sources_1/new/decoder_7seg.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/imports/sources_1/new/hex_to_7seg.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/imports/sources_1/new/mux_4bit_4to1.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/imports/sources_1/imports/new/n_bit_count.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/new/selector.v}
  {E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/sources_1/new/board_sqrt.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/constrs_1/imports/new/7seg.xdc}}
set_property used_in_implementation false [get_files {{E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/constrs_1/imports/new/7seg.xdc}}]

read_xdc {{E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/constrs_1/imports/new/pmod.xdc}}
set_property used_in_implementation false [get_files {{E:/ENEE245 Verilog code/Lab 11/sqrt/sqrt.srcs/constrs_1/imports/new/pmod.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top board_sqrt -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef board_sqrt.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file board_sqrt_utilization_synth.rpt -pb board_sqrt_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
